# Execute the playbook with Dry Run Systax i.e ansible-playbook 1b_dry_run.yml --check
---
- name: This playbook is used to restart sshd daemon and test the dry run
  hosts: dev
  tasks:
    - service:
        name: sshd
        state: restarted